// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    aggregator
    (
        init => init
        aggregate => aggregate
        getClaimabeProtocolFee => get_claimable_protocol_fee
        registerProtocolFee => register_protocol_fee
        getClaimabeAshswapFee => get_claimable_ashswap_fee
        getAshswapFeeAddress => ashswap_fee_address
        registerAshswapFee => register_ashswap_fee
        getProtocolFeePercent => protocol_fee_percent
        getAshswapFeePercent => ashswap_fee_percent
        claimProtocolFee => claim_protocol_fee
        claimProtocolFeeByTokens => claim_protocol_fee_by_tokens
        claimAshswapFee => claim_ashswap_fee
        claimAshswapFeeByTokens => claim_ashswap_fee_by_tokens
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
