[package]
name = "wrapper_view-meta"
version = "0.0.0"
authors = ["Bicarus <hello@bicarus.io>"]
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.wrapper_view]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.47.5"
