[package]
name = "token_send"
version = "0.0.0"
authors = ["Bicarus <hello@bicarus.io>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.47.5"
features = ["esdt-token-payment-legacy-decode"]
