[workspace]
resolver = "2"
members = [
    "dex",
    "dex/aggregator",
    "dex/aggregator/meta",
    "dex/wrapper_view",
    "dex/wrapper_view/meta",
    "dex/wrapper-mock",
    "dex/wrapper-mock/meta",
    "dex/fee",
    "dex/fee/meta",
]
