[package]
name = "wrapper-mock-meta"
version = "0.0.0"
authors = ["Bicarus <hello@bicarus.io>"]
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.wrapper-mock]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.40.0"
