// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    wrapper_view
    (
        init => init
        getAshswapV1 => get_ashswapv1
        getAshswapV2 => get_ashswapv2
        getJexExchange => get_jexexchange
        getOnedex => get_onedex
        getXExchange => get_xexchange
        getHatom => get_hatom
        getTinder => get_tinder
        getHatomLiquidStaking => get_hatom_liquid_staking
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
