[package]
name = "aggregator-meta"
version = "0.0.0"
authors = ["Bicarus <hello@bicarus.io>"]
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.aggregator]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.47.7"
