[package]
name = "wrapper-mock"
version = "0.0.0"
authors = ["Bicarus <hello@bicarus.io>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.47.7"
features = ["esdt-token-payment-legacy-decode"]
